<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\ListboxField;
    use SilverStripe\ORM\ArrayList;
    use SilverStripe\View\ArrayData;

    class QIProjectPage extends Page
    {
        private static $icon_class = 'font-icon-block-content';

        private static $db = [
            'Year' => 'Varchar(255)'
        ];

        private static $has_one = [
            'FeaturedImage' => Image::class
        ];

        private static $many_many = [
            'RelatedProjects' => QIProjectPage::class,
            'Categories'      => QIProjectCategory::class
        ];

        private static $owns = [
            'FeaturedImage'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', UploadField::create('FeaturedImage')
                ->setFolderName('QIProjectPage/Featured_Image'),'Sections');
            $fields->addFieldToTab('Root.Main', ListboxField::create('RelatedProjects', 'Related projects',
                QIProjectPage::get()->filter('Title:not', $this->owner->Title)->map("ID", "Title")),'FeaturedImage');
            $fields->addFieldToTab('Root.Main', ListboxField::create('Categories', 'Categories',
                QIProjectCategory::get()->filter('Archived', false)->map("ID", 'Title')),'FeaturedImage');
            $fields->addFieldToTab('Root.Main', DropdownField::create('Year', 'Year', $this->getYearFilter()->map('Name', 'Name')),'FeaturedImage');

            return $fields;
        }

        public function getYearFilter() {
            $yearLists = $this->Parent()->FilterYear;
            $years    = explode(",",$yearLists);

            $output = new ArrayList();
            foreach($years as $year) {
                $output->push(
                    new ArrayData(array('Name' => $year))
                );
            }
            return $output;
        }
    }
}
