<?php

namespace {

    use SilverStripe\Forms\GridField\GridField;
    use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
    use SilverStripe\Forms\TextareaField;
    use SilverStripe\ORM\ArrayList;
    use SilverStripe\View\ArrayData;

    class QIProjectHolderPage extends Page
    {
        private static $icon_class = 'font-icon-menu-campaigns';

        private static $default_child = QIProjectPage::class;

        private static $allowed_children = [
            QIProjectPage::class
        ];

        private static $db = [
            'FilterYear' => 'Text'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

            $fields->addFieldToTab('Root.Main', TextareaField::create('FilterYear', 'Year filter')
                ->setDescription('Add comma in each year for separation (E.g. 2017,2018)'), 'Sections');
            /**
             * QI Project Categories
             */
            $config = GridFieldConfig_RecordEditor::create('999');
            $editor = GridField::create('QIProjectCategory', 'Project categories', QIProjectCategory::get(), $config);
            $fields->addFieldToTab('Root.ProjectCategories', $editor);

            return $fields;
        }

        public function getAllYears()
        {
            $yearLists =  $this->FilterYear;
            $years    = explode(",",$yearLists);

            $output = new ArrayList();
            foreach($years as $item) {
                $output->push(
                    new ArrayData(array('name' => $item))
                );
            }
            return $output;
        }

        public function getVisibleQIProjectCategories()
        {
            return QIProjectCategory::get()->filter('Archived', false)->sort('Sort');
        }
    }
}
