<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\GridField\GridField;
    use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
    use Symbiote\GridFieldExtensions\GridFieldEditableColumns;
    use Symbiote\GridFieldExtensions\GridFieldOrderableRows;

    class ResourcesHolderPage extends Page
    {
        private static $icon_class = 'font-icon-p-book';

        private static $default_child = ResourcesPage::class;

        private static $allowed_children = [
            ResourcesPage::class
        ];

        private static $has_many = [
            'Filters' => Filter::class
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $gridConfig = GridFieldConfig_RecordEditor::create(999);
            if($this->Filters()->Count())
            {
                $gridConfig->addComponent(new GridFieldOrderableRows());
            }
            $gridConfig->addComponent(new GridFieldEditableColumns());
            $gridColumns = $gridConfig->getComponentByType(GridFieldEditableColumns::class);
            $gridColumns->setDisplayFields([
                'Archived' => [
                    'title' => 'Archive',
                    'callback' => function($record, $column, $grid) {
                        return CheckboxField::create($column);
                    }]
            ]);

            $gridField = GridField::create(
                'Filters',
                'Filters',
                $this->Filters(),
                $gridConfig
            );

            $fields->removeByName("Filters");
            $fields->addFieldToTab('Root.Filter', $gridField);
            return $fields;
        }

        public function getVisibleFilters()
        {
            return $this->Filters()->filter('Archived', false)->sort('Sort');
        }
    }
}
