<?php

namespace {

    use Bummzack\SortableFile\Forms\SortableUploadField;
    use CWP\CWP\PageTypes\NewsPage;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\ListboxField;
    use SilverStripe\Forms\TextField;

    class StaffPage extends Page
    {
        private static $icon_class = 'font-icon-torso';

        private static $db = [
            'Position'     => 'Varchar',
            'Blob'         => 'Text',
            'TeamCategory' => 'Varchar'
        ];

        private static $has_many = [
            'Socials' => Socials::class
        ];

        private static $many_many = [
            'ProfileImages' => Image::class
        ];

        private static $belongs_many_many = [
            'Postings' => NewsPage::class
        ];

        private static $owns = [
            'ProfileImages'
        ];

        private static $many_many_extraFields = [
            'ProfileImages' => ['SortOrder' => 'Int']
        ];

        function TeamCategories()
        {
            return array('i3','eCALD','Safety in Practice','Alumni','Clinical Leader','Fellow','Intern','Contractor');
        }

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', TextField::create('Position'),'Sections');
            $fields->addFieldToTab('Root.Main', ListboxField::create('TeamCategory', 'Team category', $this->TeamCategories()), 'Sections');
            $fields->addFieldToTab('Root.Main', SortableUploadField::create('ProfileImages', 'Profile Images')
                ->setFolderName('StaffPage/'. $this->owner->Title .'/Images'),'Sections');
            return $fields;
        }
    }
}
