<?php

namespace {

    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
    use SilverStripe\Forms\TextareaField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class FooterItems extends DataObject
    {
        private static $default_sort = 'Sort ASC';

        private static $db = [
            'Name'     => 'Varchar',
            'Content'  => 'HTMLText',
            'Code'     => 'Text',
            'Width'    => 'Varchar',
            'Type'     => 'Varchar',
            'Archived' => 'Boolean',
            'Sort'     => 'Int',
        ];

        private static $summary_fields = [
            'Name',
            'Type',
            'Width',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', DropdownField::create('Type', 'Footer type',
                array(
                    'Content' => 'Content',
                    'Code'    => 'Code',
                )
            ));
            $fields->addFieldToTab('Root.Main', HTMLEditorField::create('Content')
                ->displayIf('Type')->isEqualTo('Content')->end());
            $fields->addFieldToTab('Root.Main', TextareaField::create('Code')
                ->displayIf('Type')->isEqualTo('Code')->end());
            $fields->addFieldToTab('Root.Main', DropdownField::create('Width', 'Width',
                array(
                    'col-md-2' => '16%',
                    'col-md-3' => '25%',
                    'col-md-4' => '33%',
                    'col-md-5' => '41%',
                    'col-md-6' => '50%',
                    'col-md-7' => '58%',
                    'col-md-8' => '66%',
                    'col-md-9' => '75%',
                    'col-md-10' => '83%',
                    'col-md-11' => '91%',
                    'col-md-12' => '100%',
                )
            ));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));
            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
