<?php

namespace {

    use CWP\CWP\PageTypes\NewsPage;
    use SilverStripe\Forms\FieldList;
    use SilverStripe\Forms\ListboxField;
    use TractorCow\SliderField\SliderField;

    class Blogs extends Section
    {
        private static $singular_name = 'Blog List';

        private static $db = [
            "Limit" => 'Int'
        ];

        private static $many_many = [
            'NewsPage' => NewsPage::class
        ];

        public function getSectionCMSFields(FieldList $fields)
        {
            $fields = parent::getSectionCMSFields($fields); // TODO: Change the autogenerated stub
            $fields->addFieldToTab('Root.Main', SliderField::create('Limit', 'Limit blogs to show', 2, 4));
            $fields->addFieldToTab('Root.Main', ListboxField::create('NewsPage', 'Select blog page' ,
                NewsPage::get()->Filter('NewsPageType', 'blogs')->map('ID', 'Title')));
        }
    }
}
